// <auto-generated />
namespace CrmBL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Update29102022 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update29102022));
        
        string IMigrationMetadata.Id
        {
            get { return "202210291102062_Update29102022"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
